apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-service
  template:
    metadata:
      labels:
        app: auction-service
    spec:
      containers:
        - name: auction-service
          image: nikolaiauctionhouseprojectregistry.azurecr.io/auction-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7051
          env:
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_ADDR
            - name: VAULT_ROLE
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: VAULT_ROLE
            - name: ASPNETCORE_URLS
              value: http://+:7051
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: auction-service
spec:
  selector:
    app: auction-service
  ports:
    - protocol: TCP
      port: 7051
      targetPort: 7051
  type: LoadBalancer
